default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USER"] || 'postgres' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 5 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>

development:
  <<: *default
  database: <%= ENV["POSTGRESQL_DATABASE"] || "alunos_da_obra_do_berco_development" %>

test:
  <<: *default
  database: <%= ENV["POSTGRESQL_DATABASE"] || "alunos_da_obra_do_berco_test" %>

production:
  <<: *default
  database: <%= ENV["POSTGRESQL_DATABASE"] || 'alunos_da_obra_do_berco_production' %>
